name: mesa_bloc
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  build_runner: ^2.4.14
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.7
  file_picker: ^8.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  http_parser: ^4.1.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3
  mime: ^2.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  universal_io: ^2.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/imagen/
    - assets/icons/
    - assets/imagen/grupo.svg
    - assets/imagen/undraw_finance_m6vw.svg
